FROM python:3.9
COPY ./server web

WORKDIR web 

RUN python -m pip install -r requirements.txt --no-dependencies
RUN python -m nltk.downloader punkt
RUN python -m nltk.downloader wordnet
RUN python -m nltk.downloader omw-1.4
RUN python -m nltk.downloader stopwords

RUN ./installer.sh

CMD python app.py

EXPOSE 5000
